### ISSUE TITLE
Where do I find the log file?

### ISSUE THREAD

**Issue by ErikBrown2** [Opvolger/plugin.video.hanssettings#6]
I have since today an issue that downloading the list gives issues. When I start the addon, it downloads about two or three files (of 184) and then gives an error and says that I need to check the log for more information. When I then restart the addon, again a few more files are downloaded. 

Does anybody know where I should look for the log to find the cause of the issue? I use Libreelec on a Pi and have looked around the files using WinSCP but do not find anything that looks like a logfile of Hanssettings.

**Comment by Opvolger** [comment]
With Google I found this: https://forum.libreelec.tv/thread/3004-debugging-le/

**Comment by ErikBrown2** [comment]
Dankjewel voor de info. Sinds gisteren werkt het downloaden van de lijst niet meer. Zowel op mijn PC als op mijn Raspberry Pi met Libreelec heb ik het probleem dat de addon de lijst begint te downloaden en na een paar files gedownload te hebben een foutmelding geeft. Als ik dan de addon weer opstart dan download het weer een paar extra files en geeft dan weer dezelfde foutmelding. Op de PC slaagt de addon er in om meerdere files te downloaden voordat het de fout geeft dan op de Raspberry Pi. Dus op de PC hoeft ik de addon maar een keer of tien op te starten en de lijst is uiteindelijk binnen. Maar op de Raspberry Pi gaat het trager en is het me nog niet gelukt om de lijst compleet te krijgen.

De fout die ik vind in het Kodi log van de Raspberry Pi is:

2021-01-27 19:29:01.022 T:1937260560  NOTICE: Running the application...
2021-01-27 19:29:01.221 T:1756681088  NOTICE: Register - new cec device registered on cec->RPI: CEC Adapter (2708:1001)
2021-01-27 19:31:10.910 T:1566851968   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'urllib2.URLError'>
                                            Error Contents: <urlopen error [Errno 104] Connection reset by peer>
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.hanssettings/addon.py", line 229, in <module>
                                                router(sys.argv[2][1:])
                                              File "/storage/.kodi/addons/plugin.video.hanssettings/addon.py", line 225, in router
                                                list_categories(content_type)
                                              File "/storage/.kodi/addons/plugin.video.hanssettings/addon.py", line 109, in list_categories
                                                _hanssettings.get_data_from_github_file, filename)
                                              File "/storage/.kodi/addons/script.common.plugin.cache/resources/lib/storage_server/StorageServer.py", line 623, in cacheFunction
                                                ret_val = funct(*args)
                                              File "/storage/.kodi/addons/plugin.video.hanssettings/resources/lib/hanssettings.py", line 51, in get_data_from_github_file
                                                response = urlopen(req)
                                              File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
                                              File "/usr/lib/python2.7/urllib2.py", line 429, in open
                                              File "/usr/lib/python2.7/urllib2.py", line 447, in _open
                                              File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
                                              File "/usr/lib/python2.7/urllib2.py", line 1241, in https_open
                                              File "/usr/lib/python2.7/urllib2.py", line 1198, in do_open
                                            URLError: <urlopen error [Errno 104] Connection reset by peer>
                                            -->End of Python script error report<--
2021-01-27 19:31:11.031 T:1799328640   ERROR: GetDirectory - Error getting plugin://plugin.video.hanssettings/
2021-01-27 19:31:11.034 T:1937260560   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.hanssettings/) failed

Een screenshot van de foutmelding is:

![screenshot671](https://user-images.githubusercontent.com/32511867/106019008-9642da00-60db-11eb-845e-42510775e36c.png)

**Comment by ErikBrown2** [comment]
Dit is een sectie van de Kodi log van mijn PC:

2021-01-27 19:52:32.598 T:4856   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'urllib2.URLError'>
                                            Error Contents: <urlopen error [Errno 10054] An existing connection was forcibly closed by the remote host>
                                            Traceback (most recent call last):
                                              File "C:\Users\Erik\AppData\Roaming\Kodi\addons\plugin.video.hanssettings\addon.py", line 224, in <module>
                                                router(sys.argv[2][1:])
                                              File "C:\Users\Erik\AppData\Roaming\Kodi\addons\plugin.video.hanssettings\addon.py", line 220, in router
                                                list_categories(content_type)
                                              File "C:\Users\Erik\AppData\Roaming\Kodi\addons\plugin.video.hanssettings\addon.py", line 104, in list_categories
                                                _hanssettings.get_data_from_github_file, filename)
                                              File "C:\Users\Erik\AppData\Roaming\Kodi\addons\script.common.plugin.cache\resources\lib\storage_server\StorageServer.py", line 623, in cacheFunction
                                                ret_val = funct(*args)
                                              File "C:\Users\Erik\AppData\Roaming\Kodi\addons\plugin.video.hanssettings\resources\lib\hanssettings.py", line 51, in get_data_from_github_file
                                                response = urlopen(req)
                                              File "C:\Program Files\Kodi\system\python\Lib\urllib2.py", line 154, in urlopen
                                                return opener.open(url, data, timeout)
                                              File "C:\Program Files\Kodi\system\python\Lib\urllib2.py", line 429, in open
                                                response = self._open(req, data)
                                              File "C:\Program Files\Kodi\system\python\Lib\urllib2.py", line 447, in _open
                                                '_open', req)
                                              File "C:\Program Files\Kodi\system\python\Lib\urllib2.py", line 407, in _call_chain
                                                result = func(*args)
                                              File "C:\Program Files\Kodi\system\python\Lib\urllib2.py", line 1241, in https_open
                                                context=self._context)
                                              File "C:\Program Files\Kodi\system\python\Lib\urllib2.py", line 1198, in do_open
                                                raise URLError(err)
                                            URLError: <urlopen error [Errno 10054] An existing connection was forcibly closed by the remote host>
                                            -->End of Python script error report<--
2021-01-27 19:52:32.648 T:972   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.hanssettings/?content_type=video
2021-01-27 19:52:32.652 T:6012   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.hanssettings/?content_type=video) failed

**Comment by Opvolger** [comment]
Bij mij lijkt alles te werken, welke versie van Kodi gebruik je?
Ik draai zelf onder Linux, maar zal zo een Windows machine aanslingeren en kijken wat die doet... Maar ben bang dat het in je eigen internetconnectie ligt.
- An existing connection was forcibly closed by the remote host
- Connection reset by peer
Voelen mij aan als connectie problemen, welke in hier niet kan na spelen.

**Comment by ErikBrown2** [comment]
Hi Bas, ik gebruik op de PC  en ook de Raspberry Pi Kodi 18.9. De connection reset, is het de server kant die dat veroorzaakt of kan dat ook in Kodi veroorzaakt worden? Mijn internet verbinding heeft een nogal hoge latency maar ik zou verwachten dat de server waar de lijst van gedownload wordt niet zo'n snelle timeout heeft. En verder heeft mijn internet verbinding geen problemen.

Wat ook opvalt is dat ik de volledige lijst kan downloaden op de PC door de addon iets van 10 keer weer op te starten. Telkens worden een redelijk aantal files gedownload voordat de fout optreedt. Maar voor de Raspberry Pi moet ik de addon wel ongeveer 70 keer weer opstarten voordat alle files van de lijst gedownload zijn. Dus dat lijkt mij te wijzen op een timeout van de lijst server omdat de PC sneller op de ontvangst van elke file zal reageren.

Ik woon in een wat minder vrij land in het Midden Oosten waar veel websites geblokkeerd worden maar ik kan zonder problemen naar de website https://www.detransponder.nl/kanalenlijsten/ gaan met mijn webbrowser op de PC. Kun jij me vertellen welke URL jij gebruikt in de addon voor de lijst zodat ik exact dezelfde URL kan proberen in een webbrowser om te zien of de overheid hier het blokkeert?

**Comment by Opvolger** [comment]
https://github.com/Opvolger/plugin.video.hanssettings/blob/master/resources/lib/hanssettings.py zie regel 45, ik haal alles van zijn github af.

**Comment by Opvolger** [comment]
ik zal een retry stukje maken, welke 11x probeerd de file te downloaden. hopen dat dat voor je werkt.

**Comment by Opvolger** [comment]
Probeer eens versie 2.2.6

**Comment by ErikBrown2** [comment]
Hartelijk bedankt voor de fix Bas. Dit werkt! En het lijkt er op dat het inderdaad de overheid is hier die blijkbaar de lijst subversief vindt want de link voor de file werkt ook niet met Chrome. Zie de screenshots. 
Nogmaals heel erg bedankt voor de oplossing.

<img width="960" alt="Screenshot 2021-01-31 011447" src="https://user-images.githubusercontent.com/32511867/106368270-d6b38980-6361-11eb-83ec-ddaee232b8bb.png">


<img width="960" alt="Screenshot 2021-01-31 011447" src="https://user-images.githubusercontent.com/32511867/106368908-c2be5680-6366-11eb-86dc-3e4606c728f5.png">
